GET http://localhost:8080/articles
Content-Type: application/json

###

GET http://localhost:8080/articles/comments/2
Content-Type: application/json

###

POST http://localhost:8080/articles/comments/2
Content-Type: application/json

{
  "username": "febriadji",
  "email": "iamfebriadji@gmail.com",
  "comment": "thank you for sharing this article"
}

###

GET http://localhost:8080/articles/penggunaan-method-method-pada-array-javascript
Content-Type: application/json